### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by hbf** [jaliss/securesocial#167]
Are there any plans to add LDAP authentication (against an external LDAP server)?

Maybe something like https://www.unboundid.com/products/ldap-sdk/ could easily be integrated (I'd be happy to contribute in case somebody volunteers to review the code).

**Comment by erip** [comment]
Can someone point me in the direction of some docs that show how to do this? I've looked through the docs, but couldn't seem to find LDAP auth.

**Comment by kflorence** [comment]
+1
