### ISSUE TITLE
Is there a plan to support async?

### ISSUE THREAD

**Issue by brianwawok** [jaliss/securesocial#193]
Play framework with a synchronous API does not make a ton of sense... as soon as you hit 1 DB read, you lose the NIO magic of netty.

http://reactivemongo.org/ does a good job of making a mongoDB driver be async. I think there are some various async drivers for other databases as well....

To implement it with securesocial, we would need the UserAService API to change. 

The API would need to be tweaked like this:

``` scala
  def find(id: UserId): Future[Option[Identity]] 

  def findByEmailAndProvider(email: String, providerId: String): Future[Option[Identity]]

  def save(user: Identity): Future[Identity]

  def findToken(tokenId: String): Future[Option[Token]]
```

**Comment by sameerparekh** [comment]
Hello. According to the documentation here:

http://securesocial.ws/guide/user-service.html

The UserService is still not async. 

What am I missing?

Thanks.
