### ISSUE TITLE
Multiple scopes to facebook

### ISSUE THREAD

**Issue by ElielBarone** [jaliss/securesocial#196]
Hi. How can I define a lot of scopes from facebook for my secureSocial? I'm using a publish_actions, but new users cannot do a sign in. I need change scope for email, but I need the publish scope too.

scope=email - to sign in
scope=publish_actions - to publish

I was trying:

scope=email,publish_actions

but it not work

thanks

**Comment by faberchri** [comment]
Didn't find the answer in the SO link, but this worked for me:
```
scope="email,user_photos"
```
