### ISSUE TITLE
Email only sent in Debug or Run mode

### ISSUE THREAD

**Issue by buggtb** [jaliss/securesocial#347]
This is a strange report, and I have no idea where the problem really lies but I figure I should probably at least make people aware of it.

I use UsernamePassword auth and I want to Unit Test the Welcome Email that gets sent out to make sure it contains the right details and so I can Unit test the rest of the login mechanism so I need the URL included within it.

My app works, and emails are sent, that much I know, but when I do:
play test
emails aren't send, but if I do 
play debug => test
emails are dispatched once again.

No idea why, but worth mentioning.

Tom

**Comment by jaliss** [comment]
Still experiencing this? Please re-open if needed.
