### ISSUE TITLE
Login Flow from Android and iOS

### ISSUE THREAD

**Issue by ghost** [jaliss/securesocial#365]
I want to use the native login flow (App oauth, so people dont have to open a browser to auth), so i have implemented google and facebook auth with the SDK, they retrieve me a Token, so i want to modify GoogleProvider.scala and FacebookProvider.scala to send the token when it do the method  val call = WS.url(MeApi + accessToken).get(), i just need to put my AccessToken, and then it will work like WEB. So, what do you Think?
Is possible?

**Comment by jmrodrig** [comment]
Hi, ghost!
I want to do the same has you did. I want to try the solution you've posted but I dunno where, in the project file system (app/controllers??) to put that file and, since my server is all in java, do I have to re-write your scala code to java?
