### ISSUE TITLE
idLengthInBytes Option Being Ignored

### ISSUE THREAD

**Issue by sirsavary** [jaliss/securesocial#451]
I am trying to use Memcached instead of the default Play cache but I am running into issues with the ids generated by Secure Social being too long. I discovered that you can specify a length option in the application.conf and did so, setting the length to 100. I still received the maxlength errors so I tried setting it to 10 to no avail. I added a bit of debug code to see if the option was even being read by play and it was.

The exact line in my config is: securesocial.idLengthInBytes=10

I even dug through the source of IdGenerator to make sure I was using the proper key.

**Comment by http-teapot** [comment]
@chris-cooper it worked, thank you very much, I've been struggling on this for the past 2 hours.
