### ISSUE TITLE
main.scala.html uses hardcoded bootstrap/css/bootstrap.min.css

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [jaliss/securesocial#467]
See:
https://github.com/jaliss/securesocial/blob/master/module-code/app/securesocial/views/main.scala.html#L8

Probably instead should expose  ```env.routes.bootstrapPath``` similar to env.routes.jqueryPath etc

**Comment by mingchuno** [comment]
Agree with that, I now have to manually duplicate my `stylesheets/bootstrap.min.css` to `bootstrap/css/bootstrap.min.css`

**Comment by jaliss** [comment]
This was done in #489
