### ISSUE TITLE
Users getting logged out on multiple servers/machines (Heroku scaling)

### ISSUE THREAD

**Issue by svasconcelos** [jaliss/securesocial#483]
I've been trying to solve this issue for some time now, but I can't seem to find the proper answer for this.

I have an app on Heroku I need to scale, however if I do it the users will be logged out if a request is not processed by the machine that initially authenticated the user.

I need to find a way to persist the authentication cookie on the DB (instead of cache) or something like that, but I'm not sure how to do it.

Can someone please point me in the right direction? I'm using Play Framework 2.2.2 with SecureSocial 2.1.3.

Thanks in advance.

**Comment by jamesallchin** [comment]
@svasconcelos Any chance you could share what you did with your scala code to overcome this problem? Thanks, James

**Comment by svasconcelos** [comment]
create table authenticator (
 id                        text,
 userId                    varchar(255),
 provider                  varchar(255),
 creationDate              timestamp,
 lastUsed                  timestamp,
 expirationDate            timestamp,
 constraint pk_authenticator primary key (id))
;

create sequence authenticator_seq;

------------------------------------------------------------

DefaultAuthenticatorStore.scala as follows:

package helper;

import _root_.java.security.SecureRandom
import org.joda.time.DateTime
import play.api.libs.Codecs
import play.api.{Play, Application, Plugin}
import com.typesafe.plugin._
import Play.current
import play.api.cache.Cache
import play.api.mvc.{DiscardingCookie, Cookie}
import securesocial.core.{Identity,IdentityId,IdentityProvider,Authenticator,AuthenticatorStore}
import _root_.java.sql.Date
import _root_.java.sql.{Connection, Driver, DriverManager}
import _root_.java.util.Date

class DefaultAuthenticatorStore(app: Application) extends AuthenticatorStore(app) {
  def save(authenticator: Authenticator): Either[Error, Unit] = {

   val db = DriverManager.getConnection("jdbc:postgresql://localhost/kis","postgres", "postgres_admin")

   val st = db.createStatement

   val res = st.executeQuery("SELECT * from authenticator WHERE id = '" + authenticator.id + "'")
  
   /* USER EXISTS, UPDATE */
   if(res.next) {

      val upd = db.prepareStatement("UPDATE authenticator SET id = ?, userId = ?, provider = ?, creationDate = ?, lastUsed = ?, expirationDate = ? WHERE id = '" + authenticator.id + "'")
 
      upd.setString(1, authenticator.id)
      upd.setString(2, authenticator.identityId.userId)
      upd.setString(3, authenticator.identityId.providerId)
      upd.setDate(4, new java.sql.Date(authenticator.creationDate.toDate().getTime()))
      upd.setDate(5, new java.sql.Date(authenticator.lastUsed.toDate().getTime()))
      upd.setDate(6, new java.sql.Date(authenticator.expirationDate.toDate().getTime()))
      upd.executeUpdate

      /* USER DOES NOT EXIST, CREATE */
   } else {

       val q = db.prepareStatement("INSERT INTO authenticator (id, userId, provider, creationDate, lastUsed, expirationDate) VALUES (?,?,?,?,?,?)")

       q.setString(1, authenticator.id)
       q.setString(2, authenticator.identityId.userId)
       q.setString(3, authenticator.identityId.providerId)
       q.setDate(4, new java.sql.Date(authenticator.creationDate.toDate().getTime()))
       q.setDate(5, new java.sql.Date(authenticator.lastUsed.toDate().getTime()))
       q.setDate(6, new java.sql.Date(authenticator.expirationDate.toDate().getTime()))
       q.executeUpdate
   }

    db.close
    Right(())
  }

  def find(id: String): Either[Error, Option[Authenticator]] = {

   val db = DriverManager.getConnection("jdbc:postgresql://localhost/kis","postgres", "postgres_admin")

   val st = db.createStatement

   val res = st.executeQuery("SELECT * from authenticator WHERE id = '" + id + "'")

   val authenticator = if(res.next) Some(Authenticator(res.getString("id"), IdentityId(res.getString("userId"), res.getString("provider")), new DateTime(res.getDate("creationDate")), new DateTime(res.getDate("lastUsed")), new DateTime(res.getDate("expirationDate")))) else None

    db.close
    Right((authenticator))
  }

  def delete(id: String): Either[Error, Unit] = {

    val db = DriverManager.getConnection("jdbc:postgresql://localhost/kis","postgres", "postgres_admin")

    val del = db.prepareStatement("DELETE FROM authenticator WHERE id = '" + id + "'")
    del.executeUpdate
    db.close

    Right(())
  }
}

Let me know if it works.

Cheers

**Comment by jamesallchin** [comment]
Cool thanks a lot. I will adapt for mongo (with reactivemongo) and post back what we did. Thanks, James

**Comment by odroz** [comment]
Hi @jamesallchin any chance you've come up with a solution for reactivemongo? I'd definitely be interested ;-)
Thanks a lot
