### ISSUE TITLE
Unmerged PRs

### ISSUE THREAD

**Issue by fignuts** [jaliss/securesocial#498]
There are 32 unresolved PRs now on this repo and there have been no commits for over 3 months. @jaliss if you do not have time to merge these is it possible for you to add somebody else as a collaborator who might be able to? I would volunteer but I don't feel that I have enough scala/java experience to do the job properly. I really like this project and I am eager to see it move forward!

**Comment by jaliss** [comment]
I'm catching up on things @fignuts
