### ISSUE TITLE
Custom Not Authorized page

### ISSUE THREAD

**Issue by finalspy** [jaliss/securesocial#499]
I'm trying to customize the 403 not authorized page used by securesocial.
Not sure if I'm in the right direction cause I encounter an issue that I'm stuck on.
(I'm using securesocial 2.1.2 with a play2 java version)

What I did : 
Create a CustomAuthorization implement Authorization and @Override isAthorized method.
Add  @SecureSocial.SecuredAction(authorization = CustomAuthorization.class)
Add a CustomTemplatePlugin and define getNotAuthorizedPage to point to my custm view

Until there everything is OK

What I need : 
get the user in the not authorized page to personalized the error message

What I tried : 
getting the identity inside the getNotAuthorized method : 
val userName = request.user match {
      case Some(user) => user.fullName
      case _ => "guest"
    }

but it seems request.user isn't recognized.

How should I achieve this ? Did I misunderstood something or is it a bug ?

**Comment by rock1984** [comment]
To customize, we have a class that extends the ViewsPlugin.scala.
Apparently SecureSocial is not using `getNotAuthorizedPage` method of ViewsPlugin.scala. Searched the sources and no one is calling. I also saw that in DefaultSecuredActionResponses.java and SecureSocial.scala classes is fixed the `securesocial.views.html.notAuthorized` url.

Can you fix this please?

**Comment by bonnlei** [comment]
I use 
def getNotAuthorizedPage(implicit request: RequestHeader, lang: Lang): Html = {
    views.html.custom.notAuthorized()(request, defaultLang, env)
  }
to customize" Not Authorized Page". but only it displays still original view. 
Why do you use "def" not "override def" in your ViewTemplates.Default class?
