### ISSUE TITLE
Please add redirect-setting in case user cancels authorization

### ISSUE THREAD

**Issue by mkurz** [jaliss/securesocial#500]
Please add a setting which controls where a user gets redirected to after he/she cancels the authorization process (e.g. after clicking "Cancel" on the Facebook Login Page)

For more info see [these few comments here](https://github.com/jaliss/securesocial/issues/468#issuecomment-66515660).

**Comment by marad** [comment]
It has been almost a year. Is there any chance for having this setting implemented?

**Comment by eximius313** [comment]
+1

**Comment by jaliss** [comment]
Added an accessDeniedUrl method in routes service that you can override.  Let me know how it goes.

**Comment by mkurz** [comment]
@jaliss Thanks! I am not using securesocial right now but thank you anyway!
