### ISSUE TITLE
Exceptions without message not very useful

### ISSUE THREAD

**Issue by francisdb** [jaliss/securesocial#509]
I've seen the below exceptions occurring on my website and this exception could alt least use an error message. An even better fix would be to not throw an exception for this case.

    securesocial.core.AuthenticationException
        at securesocial.core.OAuth2Provider$$anonfun$5.apply(OAuth2Provider.scala:118)

I would force to provide a message for these AuthenticationExceptions
https://github.com/jaliss/securesocial/blob/master/module-code/app/securesocial/core/OAuth2Provider.scala#L118

**Comment by jaliss** [comment]
@francisdb this should have been addressed in #550. Please re-open if needed. Thanks.
