### ISSUE TITLE
RuntimeEnvironment should use def instead of val for abstract members

### ISSUE THREAD

**Issue by danielkza** [jaliss/securesocial#512]
The `RuntimeEnvironment` trait has all it's components as `val`. That means they cannot be overriden by a `def`s or `lazy val`, removing quite a bit of flexibility. For example, I wanted each of my controllers to register an event listener if desired, and do user-aware actions from some of them. But that is not possible because `eventListeners` is immutable. It also happens to be a `List` when it should be a `Seq` so it could be overridden by any type of collection.

**Comment by jaliss** [comment]
@danielkza just implemented this. thanks.
