### ISSUE TITLE
Clean-up session upon auto-login after sign-up

### ISSUE THREAD

**Issue by phammer** [jaliss/securesocial#516]
There is no clean-up of the session after the sign-up (if `signupSkipLogin=true`). The clean-up is performed for normal logins, but not in the mentioned case. See `Registration.scala:197`.

Based on the implementation for the login, the code below would do the job.

```
confirmationResult()
  .flashing(Success -> Messages(SignUpDone))
  .withSession(eventSession - SecureSocial.OriginalUrlKey - IdentityProvider.SessionId)
  .startingAuthenticator(authenticator)
```

**Comment by phammer** [comment]
Forgot to mention. We stumbled over this because old values of `original-url` where still in the session after a logout and thus, the next user was redirected again to the page stored on `original-url`.

@jaliss : I was wondering why there is no clean-up of the session upon logout. Wouldn't it be better to leave the session in a clean (without SecureSocial data) after a logout?

**Comment by jaliss** [comment]
yes @phammer ... we should remove all values set by the module.
