### ISSUE TITLE
Play 2.3.7

### ISSUE THREAD

**Issue by diego04** [jaliss/securesocial#520]
Hi jaliss,

All of the authentication method works.
Although, I cant send email for registration
Ive tried manually sending emails using my own class so I know my own configuration works.

Ive used this as a guide
http://www.filtercode.com/play/play-scala-securesocial

Is it possible for you to show your configurations or check if this master branch (3.0-M1) is working for sending emails for registration?

Thanks

**Comment by jaliss** [comment]
emails are working fine in the sample apps, please double check your config against the samples and re-open if needed.
