### ISSUE TITLE
email not sent even with the sample app

### ISSUE THREAD

**Issue by zengzhu** [jaliss/securesocial#524]
in http://localhost:9000/auth/signup

email is not sent .

smtp {
	host = smtp.exmail.qq.com
	port = 465
	ssl=true
	user = some sender
	password = some password
	auth = true
}

**Comment by sgift** [comment]
Add from = "Some.email@somehost.com" - it is missing but required, which leads to a NoSuchElementException in the socialsecure mailer plugin, when it tries to send the register mail.
e.g.

smtp {
host = smtp.exmail.qq.com
port = 465
ssl=true
from = some sender
user = some sender
password = some password
auth = true
}

**Comment by jaliss** [comment]
This is working for me. Please re-open if needed.
