### ISSUE TITLE
Play 2.3.8

### ISSUE THREAD

**Issue by nightrise** [jaliss/securesocial#529]
Hi jaliss,

Do you think we could get a new build supporting Play 2.3.8? It seems the major difference is with async-http-client that was updated. Changelog is here: https://www.playframework.com/changelog

Thank you, and great work again man!

**Comment by hohl** [comment]
+1

**Comment by jaliss** [comment]
do you guys still need this?

**Comment by nightrise** [comment]
I managed to get past this, I forget how, so for me the answer is no :).

**Comment by hohl** [comment]
No.

**Comment by jaliss** [comment]
Ok, will close this then. Thanks @nightrise @hohl
