### ISSUE TITLE
Event: Sealed Trait doesn't allow custom events

### ISSUE THREAD

**Issue by nightrise** [jaliss/securesocial#530]
Hi jaliss,

I wanted to add a custom event to track email changes, but sadly it seems like it isn't possible to extend the "Event" class outside the actual file it's defined due to it being marked as "sealed".

Is there a practical or security reason for this? It would be very nice to be able to add however many custom events and react to them via the EventListener.

**Comment by jaliss** [comment]
You are right @nightrise. It would be much useful not to have a sealed trait.

**Comment by jaliss** [comment]
just added this to master. Thanks for the suggestion @nightrise
