### ISSUE TITLE
SecuredAction ajaxCall replacement

### ISSUE THREAD

**Issue by sejkorat** [jaliss/securesocial#538]
Hi Jaliss,

Is there any replacement in the latest version for ajaxCall property? I would get status 401 when I call SecuredAction from ajax.

Thanks,
Tomas

**Comment by hohl** [comment]
vote up, would need that too

**Comment by jaliss** [comment]
SecuredAction uses content negotiation now.  See the notAuthenticatedResult and notAuthorizedResult in the SecureSocial trait for Scala. For the Java API there's a responses parameter in the SecuredAction annotation that takes care of that (see the SecuredActionResponses interface too)
