### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by JA-VON** [jaliss/securesocial#542]
Read from stdout: C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:19: object RuntimeEnvironment is not a member of package securesocial.core
C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:19: object RuntimeEnvironment is not a member of package securesocial.core
Read from stdout: import securesocial.core.RuntimeEnvironment
import securesocial.core.RuntimeEnvironment
Read from stdout: ^
       ^
Read from stdout: C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:20: object services is not a member of package securesocial.core
C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:20: object services is not a member of package securesocial.core
Read from stdout: import securesocial.core.services.UserService
import securesocial.core.services.UserService
Read from stdout: ^
                         ^
Read from stdout: C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:22: not found: value RuntimeEnvironment
C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:22: not found: value RuntimeEnvironment
Read from stdout: class MyEnvironment extends RuntimeEnvironment.Default[DemoUser] {
class MyEnvironment extends RuntimeEnvironment.Default[DemoUser] {
Read from stdout: ^
                            ^
Read from stdout: C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:23: not found: type UserService
C:\Users\Javon\Desktop\hello-play-java\app\service\MyEnvironment.scala:23: not found: type UserService
Read from stdout: override val userService: UserService[DemoUser] = new InMemoryUserService()
  override val userService: UserService[DemoUser] = new InMemoryUserService()
Read from stdout: ^
                            ^
Read from stdout: C:\Users\Javon\Desktop\hello-play-java\app\service\InMemoryUserService.java:38: securesocial.core.java.BaseUserService does not take type parameters
C:\Users\Javon\Desktop\hello-play-java\app\service\InMemoryUserService.java:38: securesocial.core.java.BaseUserService does not take type parameters
Read from stdout: public class InMemoryUserService extends BaseUserService<DemoUser> {
public class InMemoryUserService extends BaseUserService<DemoUser> {
Read from stdout: ^
                                         ^
Read from stdout: 5 errors found
5 errors found
Read from stdout: (compile:compileIncremental) Compilation failed
(compile:compileIncremental) Compilation failed

**Comment by jaliss** [comment]
Still having problems? Please re-open if needed.
