### ISSUE TITLE
[error] application - [securesocial] can't find provider for id userpass

### ISSUE THREAD

**Issue by vivenkat** [jaliss/securesocial#546]
I am trying to integrate Facebook with a sample play framework application and i get the following error when i press login: 

2015-04-25 14:04:35,268 - [ERROR] - from application in play-akka.actor.default-dispatcher-4 
Unable to log user in. An exception was thrown
securesocial.core.AuthenticationException: null

**Comment by jaliss** [comment]
Are you still facing this issue? Please re-open is so.
