### ISSUE TITLE
Demo project in Scala missing assets

### ISSUE THREAD

**Issue by PhilAndrew** [jaliss/securesocial#548]
I tried to run the demo project, the assets didn't display.

I added this to sbt build 
"ws.securesocial" %% "securesocial" % "master-SNAPSHOT" classifier "assets",

it worked.

https://groups.google.com/forum/#!topic/securesocial/DYVZMT1yC2E

**Comment by jaliss** [comment]
Thanks @PhilAndrew. Assets are not included in the main jar of the distribution.  You should not need to use the assets classifier anymore.
