### ISSUE TITLE
SecuredUserAwareAction

### ISSUE THREAD

**Issue by hohl** [jaliss/securesocial#555]
It would be nice to have something like `SecuredUserAwareAction` in SecureSocial 3.

**Comment by akkie** [comment]
What would you try to achieve with such an action?

**Comment by hohl** [comment]
When having something like:

    package controllers
    
    import models.{RemoteEndpoint, Account, Connection}
    import securesocial.core.RuntimeEnvironment
    
    class Connections(override implicit val env: RuntimeEnvironment[Account]) extends securesocial.core.SecureSocial[Account] {
    
      def findAll = UserAwareAction { implicit request =>
        request.user match {
          case Some(account) => Ok(Connection.findByAccount(account))
          case _ => Forbidden
        }
      }
    
      def create(hostname: String, port: Int, useSSL: Boolean, displayName: String, nick: String, password: Option[String] = None) = UserAwareAction { implicit request =>
        request.user match {
          case Some(account) => Ok(Connection.create(account, RemoteEndpoint(hostname, port, useSSL), displayName, nick, password))
          case _ => Forbidden
        }
      }
    
    }

Having an `SecuredUserAwareAction` would reduce all that unnecessary match/case stuff. Just like `SecuredAction` which also has an `user` property on `request`.

**Comment by hohl** [comment]
Oh dear. I just realized `SecuredAction` already has an `user` on `request`. Nice!
