### ISSUE TITLE
SecureSocial 3.0-M3 and Play 2.4

### ISSUE THREAD

**Issue by hohl** [jaliss/securesocial#556]
Just tried to upgrade my Play based web app to Play 2.4 and failed that `GlobalSettings.getControllerInsance` doesn't exist anymore.

Any workaround for that or do I need to wait for an explicit 2.4 build of SecureSocial?

```scala
  override def getControllerInstance[A](controllerClass: Class[A]): A = {
    val instance = controllerClass.getConstructors.find { c =>
      val params = c.getParameterTypes
      params.length == 1 && params(0) == classOf[RuntimeEnvironment[Account]]
    }.map {
      _.asInstanceOf[Constructor[A]].newInstance(MyRuntimeEnvironment)
    }
    instance.getOrElse(super.getControllerInstance(controllerClass))
  }
```

**Comment by hohl** [comment]
If I try to prevent this method by using dependency injection, it complains that the controllers provided by SecureSocial must use dependency injection too.

**Comment by hohl** [comment]
Tried to update the project myself (can't get it building). However if there aren't any incompatibilites I guess the only required task is to add the "@Injected()" annotation to all controllers.

**Comment by Andrei-Pozolotin** [comment]
also #466

**Comment by lloydmeta** [comment]
> Tried to update the project myself but can't get it building. However if there aren't any incompatibilities I guess the only required task is to add the "@Injected()" annotation to all controllers. (And in your application you can drop the getControllerInstance method and just mark your Environment with the @Singleton annotation.)

Does this mean that if someone wants to use SecureSocial with Play 2.4 they will need to use Guice DI as well ? :confused:

**Comment by miguelbaldi** [comment]
Actually securesocial doesn't need to depend on Guice, instead depend on JSR 330. Play 2.4 works with dependency injection in an agnostic way, relying on JSR 330, but the default implementation uses Guice (that should be transparent to securesocial). As far as I can see, securesocial is ready for DI, just need to use JSR 330 annotations.

**Comment by lloydmeta** [comment]
> As far as I can see, securesocial is ready for DI, just need to use JSR 330 annotations.

Ah, sorry, I meant to reference JSR330, not Guice in particular; for me, all runtime DI is the same: undesirable :laughing: . My concern is that Play2.4 supports compile time DI (that's the truly agnostic part), and making SecureSocial depend solely on JSR330 for DI might not be nice.

**Comment by miguelbaldi** [comment]
Play 2.4 already supports compile time DI, you could plug Macwire (https://github.com/adamw/macwire), for example. You need to extend ApplicationLoader to make use of your Macwire configuration, and use InjectedRoutesGenerator. I will try that approach and come back here to tell if I have luck with. ;-)

**Comment by lloydmeta** [comment]
> Play 2.4 already supports compile time DI

Right, that's what I mentioned. 

I was questioning whether or not the modifications to SecureSocial to support 2.4 would require the use of JSR330-style markers for the sake of run-time DI (quite a few Play projects and even internal Play APIs are hardcoded for Guice/JSR...such as `FakeApplication`). As long as SecureSocial does not come out of the box hardcoded with JSR330 as a requirement, I think everyone will be happier :D

**Comment by mullex** [comment]
I met the same issue. Anyone else has got a solution to fix this so far?

**Comment by hohl** [comment]
@mullex No. However it seems like this project has fallen asleep. If you are in hurry and need Play 2.4 support I guess you are better either adding support yourself or switching to an alternate project like [http://silhouette.mohiva.com](Silhouette) which already support Play 2.4 since months in it's latest release candiate (3.0-RC2 at the moment).

**Comment by mjrussell** [comment]
@mullex @hohl 
I'm not currently using Play 2.4 in my application, however I removed the the need for the Global.scala by extending the base controller traits with custom objects and then using a [Play Plugin](https://www.playframework.com/documentation/2.4.x/ScalaPlugins) to provide an instance of the runtime environment

I know 2.4 has deprecated the plugins, but this would be a temporary workaround while the project adds support for 2.4.

Here's an example for the controller:

```
object Auth extends BaseLoginPage[User] with BaseProviderController[User] {
  override implicit lazy val env: MainRuntimeEnvironment = AuthPlugin.getRuntimeEnvironment
}
``` 

And your routes:
```
# Login page
GET     /login                                controllers.Auth.login
GET     /logout                               controllers.Auth.logout
```

**Comment by hohl** [comment]
@mullex Thanks for the info. I tried to upgrade SecureSocial myself for 2.4, however stopped the attempted since there is much more work needed then the Dependency Injection. SecureSocial depends on multiple other parts of Play like the mailing and the localization API which also needs adoption to be able to run on Play 2.4.

**Comment by Andrei-Pozolotin** [comment]
@hohl  can you please share your experience with http://silhouette.mohiva.com?

**Comment by hohl** [comment]
I'm sorry @Andrei-Pozolotin , I've not yet used it in any project. I'm still hoping on someone else upgrading SecureSocial for Play 2.4. Refactoring an existing project to use another authentication library seemed not necessary yet.

However Silhouette looks promising. There are a quite few samples available on their homepage, so I guess getting started shouldn't be hard. If I would start a new project at the moment I would definitely use Silhouette for it.

The main difference seems to be, that SecureSocial already does stuff not directly related to the login itself, like sending "Password Reset Mails". With Silhouette you would need to implement that yourself. An advantage of Silhouette seems that it's API and source is much more cleaner and self-descriptive.

**Comment by hohl** [comment]
Any progress on Play 2.4 support?

**Comment by agapep** [comment]
+1

**Comment by eximius313** [comment]
+1

**Comment by hohl** [comment]
@Andrei-Pozolotin I've finished the transition to Silhouette over an week ago. Took me about 2 days of work for changing to Silhouette, implementing my own password reminder/email validation and upgrading my rather small project to Play 2.4. Was totally worth it!

**Comment by Andrei-Pozolotin** [comment]
@hohl great, thanks for the update

**Comment by jordancoded1** [comment]
Any idea when we will we get to use SecureSocial 3.0 for Play 2.4? :(

**Comment by nightrise** [comment]
I just updated to Scala 2.11 and Play 2.4.3 and I'm able to use Secure Social without issue so far. I'm a little paranoid though now that I see people having problems -- am I missing something? Is there a use-case I should test which is failing for others?

**Comment by vnedkov** [comment]
I was able to build a jar file from DamianoVerdone's GitHub pull request and upgrade my Java project to Play 2.4.2. I've seen no major issues related to SecureSocial so far

**Comment by dmacias** [comment]
This issue has been around for almost 4 months now, can we get an update on a timeline for Play's DI support atleast?

**Comment by AndreaPravato** [comment]
+1

**Comment by MipH** [comment]
Somebody needs hust to merge DamianoVerdone's GitHub pull request...
I'm eagerly awaiting this.

**Comment by albertostratio** [comment]
+1

**Comment by sasinda** [comment]
+1

**Comment by jaliss** [comment]
All,  I just merged @DamianoVerdone changes to support Play 2.4 (thanks Damiano!).   I've had a hard time finishing up the version I was working on so I will leave those changes for version 4.0.  

My changes would have included more API changes and that would have make it even harder to migrate.  You all have waited too long for this, so let's just minimize things for now and provide the minimal support to unblock your migrations.

The changes are available in MASTER for now.  I'll be merging a few other changes during the day. Please let me know by opening new issues if problems arise with 2.4. 

We need to update the docs so match the new changes, will try to do that soon but if someone can start helping with that it would be great.

I apologize for the slow progress and thanks again for all the great emails I've been getting from many of you expressing support for the module.
