### ISSUE TITLE
3.0m3 + play framework 2.4  has issues

### ISSUE THREAD

**Issue by Ranganaths** [jaliss/securesocial#557]
class Application(override implicit val env:RuntimeEnvironment[User]) extends securesocial.core.SecureSocial[User] {

  def index = Action { implicit  request =>
    Ok(views.html.index("uhu"));
  }

  def dashboard = Action { implicit request =>
    Ok(views.html.dashboard())
  }
}

case class User(main: BasicProfile, identities: List[BasicProfile])

The above code throws up the following exception. I am clueless how its working in the securesocial samples though.

====================================================
ProvisionException: Unable to provision, see the following errors:

1) Could not find a suitable constructor in controllers.Application. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at controllers.Application.class(Application.scala:11)
  while locating controllers.Application
    for parameter 1 at router.Routes.<init>(Routes.scala:31)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error

================================================

Not able to figure out why its trying to inject ?

thank you.

**Comment by hohl** [comment]
related to #556 and #466

**Comment by Ranganaths** [comment]
Ok, fine thank you for the reply.

**Comment by jaliss** [comment]
2.4 is available on master-SNAPSHOT now.
