### ISSUE TITLE
Currently seems impossible to `link` a userpass

### ISSUE THREAD

**Issue by blast-hardcheese** [jaliss/securesocial#564]
Based on the Scala example, I see it's possible to link new providers via something like:

```
    <a href="@env.routes.authenticationUrl(provider.id, Some(routes.Users.associateResult(provider.id).toString))">Link ${provider.id}</a>
```

... but this fails immediately when using the `userpass` provider. I attempted to special-case that provider like

```
    @if(provider.id == "userpass") {
        @securesocial.views.html.provider("userpass", Some(securesocial.core.providers.UsernamePasswordProvider.loginForm))
    } else {
        <a href="@env.routes.authenticationUrl(provider.id, Some(routes.Users.associateResult(provider.id).toString))">Link ${provider.id}</a>
    }
```

but that fails with "Invalid credentials", since that provider doesn't seem to support linking. Just writing this out has given me some ideas, I might be able to contribute a fix for this.

**Comment by blast-hardcheese** [comment]
Yeah; As far as I can see, the cleanest way to fix this would be to add something similar to `authenticateForLink`, and having a second form that has `email`/`password`/`verify`, which is used on attempted link.

As this is not a blocking issue for me, I'll disable `userpass` in the short term.

**Comment by jaliss** [comment]
That's correct @blast-hardcheese. Linking userpass is not supported right now.
