### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by mullex** [jaliss/securesocial#567]
Its been a few months since the last release. Is this project still alive?

**Comment by raunak** [comment]
A post from Jorge on Google Groups seems to suggest so - https://groups.google.com/forum/#!topic/securesocial/F9Se533PZaU

**Comment by joesan** [comment]
Even I'm curious to know the status of this project? I'm eager to use this plugin but the problem is that I use Play 2.4 and there seems to be no version at the moment that supports Play 2.4!

**Comment by jaliss** [comment]
Yes, project is alive.  Master is compatible with 2.4 as of this writing. Docs have not been updated yet but the sample apps should get you going.
