### ISSUE TITLE
Is SecureSocial still being maintained?

### ISSUE THREAD

**Issue by danielyli** [jaliss/securesocial#589]
Hey there,

This looks like an amazing library, but the most recent stable release only supports up to Play 2.2.x on Scala 2.10.x. (As of this writing, the latest are Play 2.5.2 and Scala 2.11.8.)  Play 2.2.x is [no longer on Maven](http://mvnrepository.com/artifact/com.typesafe.play/play_2.10).  Is this library still being maintained?

**Comment by k4200** [comment]
Sorry for the cross post. I have a forked version for Play 2.5 & Scala 2.11. Please check out the following if you're interested:
https://github.com/k4200/securesocial
https://oss.sonatype.org/content/repositories/snapshots/tv/kazu/securesocial_2.11/
https://oss.sonatype.org/content/repositories/releases/tv/kazu/securesocial_2.11/

The changes that I have made are a mess, but at least It's working on some sites in production.

**Comment by bchazalet** [comment]
https://github.com/mohiva/play-silhouette seems to be its successor, and partly on Jorge's work on SecureSocial.

**Comment by jaliss** [comment]
I have not abandoned the module. I resumed development recently and will start updating things.
