### ISSUE TITLE
Support latest Facebook API in Play 1.x branch

### ISSUE THREAD

**Issue by tazmaniax** [jaliss/securesocial#594]
Hi @jaliss , I have a Play1 app that uses SecureSocial and I need to add Facebook signin support. I know the Play 1.x version hasn't seen any development over the last 3 years so I was wondering how much effort it would be to update this branch to work with the latest Facebook API. Is it a major undertaking or very straight forward? I'm happy to create a pull request but before I embark I'd like to understand the feasibility. thx

**Comment by jaliss** [comment]
@tazmaniax It should not be hard. Easiest way it to create your own provider class and registering that instead of the default one.
