### ISSUE TITLE
UsernamePasswordProvider badRequest CSRF

### ISSUE THREAD

**Issue by buddhabuddy** [jaliss/securesocial#599]
When there's an empty field in the login page a badRequest is thrown in UsernamePasswordProvider. The login form has a @CSRF.formField so fails to render without CSRFAddToken at:

Results.BadRequest(viewTemplates.getLoginPage(f, msg))

How would I get a token to the render?

**Comment by jaliss** [comment]
@buddhabuddy the login page in the sample app gets the token rendered when you fail to enter one of the fields.  Could you compare/share your page to see what could be causing the problem?

**Comment by buddhabuddy** [comment]
its true it does. Sorry am on 2.5.x so its  a problem somewhere dealing with injection of CSRFAddToken.
