### ISSUE TITLE
Build breaks after new release.

### ISSUE THREAD

**Issue by shivanshuBagga** [jaliss/securesocial#600]
Hi,

Following is my configuration in build.sbt file

resolvers += Resolver.url("SecureSocial Repository", url("http://securesocial.ws/repository/snapshots/"))(Resolver.ivyStylePatterns)

and 

libraryDependencies ++= Seq(
  "ws.securesocial" %% "securesocial" % "master-SNAPSHOT" withSources(),
  "ws.securesocial" %% "securesocial" % "master-SNAPSHOT"  classifier "assets",
) 

The above configuration was working fine till 17-feb-2017,but after new release it break .
As per official forum "If you were using master-SNAPSHOT your build will break so switch to 3.0-M5."
(https://groups.google.com/forum/#!topic/securesocial/YcrAay9eO2M)

so I changed it to

libraryDependencies ++= Seq(
  "ws.securesocial" %% "securesocial" % "3.0-M5" withSources(),
  "ws.securesocial" %% "securesocial" % "3.0-M5"  classifier "assets",
) 

but even after that build failed , because in there is no different jar available for asset in 3.0-M5.
(https://repo1.maven.org/maven2/ws/securesocial/securesocial_2.11/3.0-M5/)
I also tried to downgrade to "3.0-M4"  , but same problem there .

Then i switch to "3.0-M3 , but getting error related  to "not found",please check attached file named "SecureSocial3-0-M3.txt" for full logs.
[SecureSocial3-0-M3.txt](https://github.com/jaliss/securesocial/files/785708/SecureSocial3-0-M3.txt)

I also tried to set securesocial to "3.0-M4" and asset to "3.0-M3" as
libraryDependencies ++= Seq(
  "ws.securesocial" %% "securesocial" % "3.0-M4" withSources(),
  "ws.securesocial" %% "securesocial" % "3.0-M3"  classifier "assets",
) 

But it also not worked for me.Check attached logs named "SecureSocial3-0-M4&M3.txt".
[SecureSocial3-0-M4&M3.txt](https://github.com/jaliss/securesocial/files/785713/SecureSocial3-0-M4.M3.txt)

Please help!

**Comment by jaliss** [comment]
@shivanshuBagga can you try again removing the assets dependency? That's not needed anymore.

**Comment by shivanshuBagga** [comment]
Thanks @jaliss , Its working now.

**Comment by jaliss** [comment]
Cool. You're welcome.
