### ISSUE TITLE
Support Play 2.6

### ISSUE THREAD

**Issue by kubukoz** [jaliss/securesocial#611]
Play 2.6 is out, it'd be worth checking if it's compatible with the current release and documenting it (the homepage still says "Supports Play versions 2.1.x, 2.0.x and 1.x"), and, if needed, making it so.

**Comment by normenmueller** [comment]
Yes, please open a branch for Play 2.6. For example

```
class MyController @Inject()(
  override implicit val env: MyEnvironment,
  cc: ControllerComponents
) extends AbstractController(cc)
  with securesocial.core.SecureSocial { ... }
```

causes

```
[error]   method parse in trait BaseControllerHelpers of type => play.api.mvc.PlayBodyParsers  and
[error]   lazy value parse in trait BodyParsers of type play.api.mvc.PlayBodyParsers
```

**Comment by gmethvin** [comment]
Working on this in #614. Feedback appreciated.
