### ISSUE TITLE
Can't use with Scala 2.12

### ISSUE THREAD

**Issue by ser-shant** [jaliss/securesocial#617]
I cant use it with Scala 2.12
I am getting   UNRESOLVED DEPENDENCIES  when import like this "ws.securesocial" % "securesocial_2.11" % "3.0-M3" 
 ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.play#play_2.11;2.3.7: not found
[warn]  :: com.typesafe.play#play-cache_2.11;2.3.7: not found
[warn]  :: com.typesafe.play#play-ws_2.11;2.3.7: not found
[warn]  :: com.typesafe.play#filters-helpers_2.11;2.3.7: not found
[warn]  :: com.typesafe.play.plugins#play-plugins-util_2.11;2.3.0: not found
[warn]  :: com.typesafe.play.plugins#play-plugins-mailer_2.11;2.3.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

and for "ws.securesocial" %% "securesocial" % "3.0-M3" there is missing folder on maven repository  for 2.12: 
https://mvnrepository.com/artifact/ws.securesocial/securesocial_2.12/

Is there is any specific repository to access "ws.securesocial" %% "securesocial" % "master-SNAPSHOT" using 2.12 ?

**Comment by jaliss** [comment]
@ser-shant currently master-SNAPSHOT should work with 2.12.  The artifacts are published here: https://oss.sonatype.org/content/repositories/snapshots/ws/securesocial/securesocial_2.12/master-SNAPSHOT/.

mvnrepository.com does not track snapshots as far as I understand.

**Comment by ser-shant** [comment]
@jaliss this one was very useful, thanks a lot. Probably we need to put that repo info somewhere, or I was just looking in the wrong place.
May be you could also explain where/how do we use that?
`crossScalaVersions := Common.crossScalaVersions`

It is declared in build.sbt but never used

Thanks

**Comment by jaliss** [comment]
@ser-shant if you hadd `resolvers += Resolver.sonatypeRepo("snapshots")` to your sbt file it should find the snapshot versions.

**Comment by ser-shant** [comment]
@jaliss right, it works fine for me, thanks
