### ISSUE TITLE
unknown error with google and googleoauth2

### ISSUE THREAD

**Issue by raffaeleguidi** [jaliss/securesocial#90]
I managed to get fb, twitter and userpass working with ease but I cannot get google to work in any way using either the google and the googleoauth2 provider. I tried everything you suggested in the past. The error is a UNKNOWN error, I am using play 1.2.5 and securesocial 0.2.5. 

Has google setup been tested lately? Maybe there are changes in their implementation? Or just the docs are outdated?

Thanks,
    Raffaele

**Comment by fnicollet** [comment]
Hello,

I believe I have a similar issue, even if it is an old one. I am trying to make Google OAuth 2 work but I run into this error:
00:00:00,696 ERROR ~ Error authenticating user
java.lang.IllegalStateException: Not a JSON Object: null
	at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:90)
	at securesocial.libs.ExtOAuth2.extractAccessToken(ExtOAuth2.java:111)
	at securesocial.provider.providers.GoogleOAuth2Provider.doAuth(GoogleOAuth2Provider.java:124)

I am using Play 1.3.0RC with securesocial 0.2.6 (latest at this time)

In the Google Dashboard, I have set up:
Allowed JS URL: http://localhost:9000
Redirect URL: http://localhost:9000/auth/googleoauth2 (only one in my case)

In my conf, I have only changed
securesocial.googleoauth2.clientid=*****.apps.googleusercontent.com
securesocial.googleoauth2.secret=******************************

Should it work using localhost or does it need to be available publicly online?

Thanks,
Fabien
